### PR TITLE
Implemented a popup list showing the quarkus versions returned by /api/platforms

### PR DESCRIPTION
**Pull request by cmoulliard**
- Implemented a popup list showing the quarkus versions returned by /api/platforms
- The popup list is created from the list of the platform[0].streams and set the suffix `(RECOMMENDED)` for the version recommended
- Issue: #50

### CODE REVIEW

**Comment by cmoulliard** [comment]
**Warning**: I will adapt my code to use `/api/streams` instead of `/api/platforms` - https://github.com/quarkusio/code.quarkus.io/issues/1336#issuecomment-1999389823

Using `/api/streams` will also allow us to get the list (or to populate it why not using a new UI field) of the java versions recommended, etc

**Comment by cmoulliard** [comment]
I switched the code from `/api/platforms` to `/api/streams`. I still need to test if we can now generate a zip file using the selected version. Some changes could still be needed. So just wait my go before to review @iocanel

**Review by aureamunoz — APPROVED** [review]
LGTM

**Comment by cmoulliard** [comment]
I experiment a strange issue when I review the scaffolded's values selected by a user as the value is empty for the `Quarkus version` when I click on the button review . 

Question: Do we have to save the value selected within the popup list using a specific React state which is what backstage expects to have ?

Screenshot 2024-03-19 at 10 20 12


@iocanel @aureamunoz

**Comment by iocanel** [comment]
> Question: Do we have to save the value selected within the popup list using a specific React state which is what backstage expects to have ?

I don't think so. Or at least I don't recall us doing anything similar to this for the components.

The things that we need to make sure, is that the action that creates the project from code.quarkus.io does have a field defined for reading the extension and that the template is aligned to that.

**Comment by cmoulliard** [comment]
> have a field

Yes we can use the `Stream key property` for that purpose : 
```
https://github.com/quarkusio/code.quarkus.io/blob/9d3a11b6df02d23aaa98c21105c4504f636ce268/base/src/main/java/io/quarkus/code/model/ProjectDefinitionQuery.java#L18-L21
    @QueryParam("S")
    @Parameter(name = "S", description = "The platform stream to use to create this project ('platformKey:streamId' or 'streamId')", required = false)
    @Schema(description = "The platform stream to use to create this project ('platformKey:streamId' or 'streamId')", required = false)
    String streamKey;
```
Such a key corresponds to the value `io.quarkus.platform:3.2` returned by `/api/streams`

**Comment by cmoulliard** [comment]
> I don't think so. Or at least I don't recall us doing anything similar to this for the components.

So I dont understand why then post selection within the popup list of a key `example => 3.2` the Quarkus version field is empty within the backstage review screen (see screenshots) @iocanel

**Comment by cmoulliard** [comment]
I still dont know what the final code should be BUT I can now get the version if I declare the list of the versions to be as `string[]` instead of `Version[]`
```
    const versions = ["3.2", "3.8", "3.9" ]
    // const [quarkusVersion, setQuarkusVersion] = useState<Version[]>([]);
    const [quarkusVersionStr, setQuarkusVersionStr] = useState<string[]>([]);
    
    const fetchData = async () => {
        const response = await fetch(apiStreamsUrl);
        const newData = await response.json();
        setQuarkusVersion(newData)
        setQuarkusVersionStr(versions)
    }

    function onSelectVersion(_, v) {
        console.log("Version selected: " + JSON.stringify(v))
        onChange([v.toString()]);
    }

    if (defaultQuarkusVersion) {
        return (
            <FormControl
                margin="normal"
                required={required}
                error={rawErrors?.length > 0 && !formData}
            >
                <Autocomplete
                    id="quarkus-versions"
                    options={quarkusVersionStr}
                    // getOptionSelected={(option, value) => option.key === value.key}
                    // getOptionLabel={(quarkusVersion) => userLabel(quarkusVersion)}
                    // defaultValue={setDefaultQuarkusVersionStr}
                    onChange={onSelectVersion}
                    renderInput={(params) => (
                        <TextField
                            {...params}
                            id={idSchema?.$id}
                            label="Select a quarkus version"
                            required={required}
                            placeholder={placeholder}
                            value={formData ?? ''}
                        />
                    )}
                />
            </FormControl>)
    }
```
Screenshot 2024-03-19 at 18 11 28
Screenshot 2024-03-19 at 18 11 41

**Pull request closed without merging**
